<?php get_header(); ?>
<main id="main">
	<?php if (have_posts()) : while (have_posts()) : the_post(); $image = almara_service_image_url(get_the_ID()); ?>
		<nav class="shell breadcrumbs" aria-label="Drobečková navigace"><ol><li><a href="<?php echo esc_url(home_url('/')); ?>">Domů</a></li><li><a href="<?php echo esc_url(home_url('/sluzby/')); ?>">Služby</a></li><li><span aria-current="page"><?php the_title(); ?></span></li></ol></nav>
		<section class="shell page-hero" id="top"><div class="page-hero-copy"><p class="eyebrow hero-enter"><?php echo esc_html(almara_field_value(get_the_ID(), 'eyebrow') ?: 'Na míru vašemu prostoru · ' . get_option('almara_area', 'Teplice a okolí')); ?></p><h1 class="hero-enter"><?php echo wp_kses(almara_field_value(get_the_ID(), 'heading') ?: get_the_title(), array('br' => array(), 'em' => array(), 'strong' => array())); ?></h1><p class="page-lead hero-enter"><?php echo esc_html(almara_field_value(get_the_ID(), 'lead') ?: get_the_excerpt()); ?></p><div class="page-hero-actions hero-enter"><a class="button button-primary" href="<?php echo esc_url(add_query_arg('sluzba', get_the_title(), home_url('/poptavka/'))); ?>">Nezávazně poptat <svg class="icon" aria-hidden="true"><use href="#i-arrow"/></svg></a><a class="text-link" href="<?php echo esc_url(home_url('/jak-pracujeme/')); ?>">Jak spolupracujeme <svg class="icon" aria-hidden="true"><use href="#i-arrow"/></svg></a></div><div class="page-hero-note"><svg class="icon" aria-hidden="true"><use href="#i-ruler"/></svg><span>Zaměření. Návrh. Výroba. Montáž.</span></div></div><div class="page-hero-visual hero-enter"><img src="<?php echo esc_url($image); ?>" alt="<?php echo esc_attr(get_the_title() . ' — inspirace pro váš interiér'); ?>" width="1440" height="1100" fetchpriority="high"><span>INSPIRACE &amp; ŘEMESLO</span></div></section>
		<div class="service-content"><?php the_content(); ?></div>
	<?php endwhile; endif; ?>
</main>
<?php get_footer(); ?>
